services:
  - type: web
    name: groza
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "10000"
      - key: PUBLIC_URL
        value: "https://groza-5xd1.onrender.com"
      - key: BOT_TOKEN
        sync: false
